---
title: "Manipulation"
author: "Dean Stewart"
date: "14/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
data(gapminder)
```

## Data Manipulation
begins on page 21 of learning guide for week 3

filter
```{r examples on gapminder, echo=TRUE}
gapminder_all <- read_csv("../1_data/gapminderall.csv")
gapminder_all %>% filter(!is.na(fertility))
```

select
```{r}
gapminder_all %>% select(infant_mortality, fertility)
```

Mutate
```{r}
gapminder_all_gdpcap <- gapminder_all %>%
  mutate(gdp_per_capita = gdp/population) %>%
  select(gdp_per_capita)
```

Arrange
```{r}
gapminder_all_gdpcap %>% arrange(gdp_per_capita)

#descending
gapminder_all_gdpcap %>% arrange(desc(gdp_per_capita))
```

Summarise
```{r}
gapminder_all %>% summarise(n_distinct(country))
gapminder_all %>% filter(!is.na(population)) %>%
  summarise(mean_pop = mean(population), sd_pop = sd(population))
```


Pull() or dotplaceholder
```{r}
mean_pop <- gapminder_all %>%
  filter(!is.na(population)) %>%
  summarise(mean_pop = mean(population))

class(mean_pop)

gapminder_all2 <- gapminder_all %>%
  filter(!is.na(gdp)) %>%
  mutate("gdpovermeanpop" = gdp/mean_pop) %>%
  select(gdp, gdpovermeanpop)

gapminder_all2

#this produces a whole pile of dataframes

```

need to use pull so you don't get a pile of dataframes
```{r}
# need to use .$ or pull
mean_pop <- gapminder_all %>%
  filter(!is.na(population)) %>%
  summarise(mean_pop = mean(population)) %>%
  .$mean_pop

class(mean_pop)

mean_pop <- gapminder_all %>%
  filter(!is.na(population)) %>%
  summarise(mean_pop = mean(population)) %>%
  pull(mean_pop)

class(mean_pop)

#now divide by mean_pop
gapminder_all3 <- gapminder_all %>% filter(!is.na(gdp)) %>%
  mutate("gdpovermeanpop" = gdp/mean_pop) %>%
  select(gdp, gdpovermeanpop)

gapminder_all3

```

group_by
```{r}
gapminder_all %>% group_by(continent) %>%
  filter(!is.na(gdp)) %>%
  summarise(average=mean(gdp))
```

distinct
```{r}
distinct(gapminder_all) #means all distinct and removes duplicates
distinct(gapminder_all, country, year, infant_mortality) #can also select certain columns for distinct which is differnt to the unique function - only these columns are reproduced

# Note: use duplicated() for a vector or dataframe
length(gapminder_all$country[!duplicated(gapminder_all$country)])
length(gapminder_all$country)
count(distinct(gapminder_all,country))

gapminder_allwithkey <- gapminder_all %>%
  mutate(key=paste0(country, "_", year))
#duplicated(gapminder_allwithkey)
gapminder_allwithkey$key[duplicated(gapminder_allwithkey$key)]  #this will produce any duplicates - there aren't any

#duplicated equivalent for dataframe
#I HAVE NO IDEA WHAT THIS DOES!!!
a <- gapminder_all[c(3,5),]
gapminder_dup <- rbind(gapminder_all, a)
gapminder_dup %>% mutate(dup=duplicated(gapminder_dup)) %>% filter(dup == TRUE)

b <- as.vector(duplicated(gapminder_dup))
gapminder_which_dup <- gapminder_dup[b,]
gapminder_which_dup
```

